### ISSUE TITLE
`TypeError` with `adeira/no-duplicate-import-type-import`

### ISSUE THREAD

**Issue by maicol07** [adeira/universe#3410]
I have the following error when there is a type import with the rule `adeira/no-duplicate-import-type-import`: 

```
PS C:\Users\Maicol\Documents\Projects\Web\scheduled_exams> eslint .\resources\js\_material.js

Oops! Something went wrong! :(

ESLint: 8.1.0

TypeError: Cannot read property 'type' of undefined
Occurred while linting C:\Users\Maicol\Documents\Projects\Web\scheduled_exams\resources\js\_material.js:9
Rule: "adeira/no-duplicate-import-type-import"
    at autoFix (C:\Users\Maicol\Documents\Projects\Web\scheduled_exams\node_modules\.pnpm\eslint-plugin-adeira@0.14.0\node_modules\eslint-plugin-adeira\src\rules\no-duplicate-import-type-import.js:19:36)
    at Object.fix (C:\Users\Maicol\Documents\Projects\Web\scheduled_exams\node_modules\.pnpm\eslint-plugin-adeira@0.14.0\node_modules\eslint-plugin-adeira\src\rules\no-duplicate-import-type-import.js:72:22)
    at normalizeFixes (C:\Users\Maicol\Documents\Projects\Web\scheduled_exams\node_modules\.pnpm\eslint@8.1.0\node_modules\eslint\lib\linter\report-translator.js:193:28)
    at C:\Users\Maicol\Documents\Projects\Web\scheduled_exams\node_modules\.pnpm\eslint@8.1.0\node_modules\eslint\lib\linter\report-translator.js:364:49
    at Object.report (C:\Users\Maicol\Documents\Projects\Web\scheduled_exams\node_modules\.pnpm\eslint@8.1.0\node_modules\eslint\lib\linter\linter.js:937:41)
    at ImportDeclaration (C:\Users\Maicol\Documents\Projects\Web\scheduled_exams\node_modules\.pnpm\eslint-plugin-adeira@0.14.0\node_modules\eslint-plugin-adeira\src\rules\no-duplicate-import-type-import.js:60:19)
    at ruleErrorHandler (C:\Users\Maicol\Documents\Projects\Web\scheduled_exams\node_modules\.pnpm\eslint@8.1.0\node_modules\eslint\lib\linter\linter.js:966:28)
    at C:\Users\Maicol\Documents\Projects\Web\scheduled_exams\node_modules\.pnpm\eslint@8.1.0\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (C:\Users\Maicol\Documents\Projects\Web\scheduled_exams\node_modules\.pnpm\eslint@8.1.0\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
```

Code:

```javascript
import '@material/mwc-button';
import '@material/mwc-dialog';
import '@material/mwc-drawer';
import '@material/mwc-icon-button';
import '@material/mwc-list';
import '@material/mwc-menu';
import './WebComponents/TopAppBar';
import './WebComponents/MaterialDrawer';
import type {Dialog} from "@material/mwc-dialog";
```

**Comment by michalsanger** [comment]
Hi @maicol07 I see you are using `ESLint: 8.1.0`, so just a guess if the issue could be related to missing support of ESLint 8 - #3274

To validate, could you downgrade your ESLint and check if the problem remains?

**Comment by maicol07** [comment]
I have the same issue with ESLint 7.32

**Comment by maicol07** [comment]
The same error with ESLint 7.32:

```
PS C:\Users\Maicol\Documents\Projects\Web\scheduled_exams> eslint .\resources\js\_material.js

Oops! Something went wrong! :(

ESLint: 7.32.0

TypeError: Cannot read property 'type' of undefined
Occurred while linting C:\Users\Maicol\Documents\Projects\Web\scheduled_exams\resources\js\_material.js:10
    at autoFix (C:\Users\Maicol\Documents\Projects\Web\scheduled_exams\node_modules\.pnpm\eslint-plugin-adeira@0.14.0\node_modules\eslint-plugin-adeira\src\rules\no-duplicate-import-type-import.js:19:36)
    at Object.fix (C:\Users\Maicol\Documents\Projects\Web\scheduled_exams\node_modules\.pnpm\eslint-plugin-adeira@0.14.0\node_modules\eslint-plugin-adeira\src\rules\no-duplicate-import-type-import.js:72:22)
    at normalizeFixes (C:\Users\Maicol\Documents\Projects\Web\scheduled_exams\node_modules\.pnpm\eslint@7.32.0\node_modules\eslint\lib\linter\report-translator.js:193:28)
    at C:\Users\Maicol\Documents\Projects\Web\scheduled_exams\node_modules\.pnpm\eslint@7.32.0\node_modules\eslint\lib\linter\report-translator.js:364:49
    at Object.report (C:\Users\Maicol\Documents\Projects\Web\scheduled_exams\node_modules\.pnpm\eslint@7.32.0\node_modules\eslint\lib\linter\linter.js:926:41)
    at ImportDeclaration (C:\Users\Maicol\Documents\Projects\Web\scheduled_exams\node_modules\.pnpm\eslint-plugin-adeira@0.14.0\node_modules\eslint-plugin-adeira\src\rules\no-duplicate-import-type-import.js:60:19)
    at C:\Users\Maicol\Documents\Projects\Web\scheduled_exams\node_modules\.pnpm\eslint@7.32.0\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (C:\Users\Maicol\Documents\Projects\Web\scheduled_exams\node_modules\.pnpm\eslint@7.32.0\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\Users\Maicol\Documents\Projects\Web\scheduled_exams\node_modules\.pnpm\eslint@7.32.0\node_modules\eslint\lib\linter\node-event-generator.js:293:26)
```

**Comment by mrtnzlml** [comment]
Hi @maicol07! I can indeed confirm there is a bug and I can reproduce it on a current master. Please, allow me some time for fixing it (or optionally feel free to send a PR with a fix).

Also, as @michalsanger said: the latest released version of `@adeira/eslint-config` doesn't support Eslint version 8 yet because there are still many 3rd party rules broken (not ready yet). It should be correctly specified in peer dependencies.

**Comment by mrtnzlml** [comment]
This should hopefully fix the issue: https://github.com/adeira/universe/pull/3414
